# Generated by Django 4.2.5 on 2024-01-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreshApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
