# Generated by Django 4.2.5 on 2024-01-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreshApp', '0002_register_model_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_model',
            name='gender',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
